name: check
on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]
jobs:
  mac-build:
    runs-on: mac-arm
    env:
      BEARDIST_CACHE_DIR: /tmp/beardist-cache
      BEARDIST_ARTIFACT_NAME: aarch64-apple-darwin
      PNPM_HOME: /tmp/pnpm-home
      FORGEJO_READWRITE_TOKEN: ${{ secrets.FORGEJO_READWRITE_TOKEN }}
      CLICOLOR: 1
      CLICOLOR_FORCE: 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: |
          beardist build
  linux-build:
    strategy:
      matrix:
        include:
          - runs-on: linux-amd64
            platform: linux/amd64
            artifact: x86_64-unknown-linux-gnu
            tag: latest-amd64
          - runs-on: linux-arm64
            platform: linux/arm64
            artifact: aarch64-unknown-linux-gnu
            tag: latest-arm64
    runs-on: ${{ matrix.runs-on }}
    container:
      image: code.bearcove.cloud/bearcove/beardist:${{ matrix.tag }}
      volumes:
        - /var/persistent-build-storage:/var/persistent-build-storage
      credentials:
        username: "token"
        password: "${{ secrets.BEARCOVE_PULL_PASSWORD }}"
    env:
      PNPM_HOME: /var/persistent-build-storage/pnpm-home
      BEARDIST_CACHE_DIR: /var/persistent-build-storage/beardist-cache
      BEARDIST_ARTIFACT_NAME: ${{ matrix.artifact }}
      FORGEJO_READWRITE_TOKEN: ${{ secrets.FORGEJO_READWRITE_TOKEN }}
      CLICOLOR: 1
      CLICOLOR_FORCE: 1
      IMAGE_PLATFORM: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: |
          beardist build
  trigger-formula-update:
    needs: [mac-build, linux-build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: linux-arm64
    container:
      image: code.bearcove.cloud/bearcove/beardist:latest
      credentials:
        username: "token"
        password: "${{ secrets.BEARCOVE_PULL_PASSWORD }}"
    env:
      FORGEJO_READWRITE_TOKEN: ${{ secrets.FORGEJO_READWRITE_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Trigger formula update
        run: |
          curl -f -X POST \
            -H "Authorization: token $FORGEJO_READWRITE_TOKEN" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d '{"ref": "main", "inputs": {"repository": "'$GITHUB_REPOSITORY'"}}' \
            https://code.bearcove.cloud/api/v1/repos/bearcove/tap/actions/workflows/bump.yml/dispatches
