name: check
on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]
jobs:
  mac-build:
    runs-on: depot-macos-latest
    env:
      BEARDIST_CACHE_DIR: /tmp/beardist-cache
      BEARDIST_ARTIFACT_NAME: aarch64-apple-darwin
      PNPM_HOME: /tmp/pnpm-home
      GH_READWRITE_TOKEN: ${{ secrets.GH_READWRITE_TOKEN }}
      CLICOLOR: 1
      CLICOLOR_FORCE: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: /tmp/beardist-cache
          key: ${{ runner.os }}-${{ matrix.artifact }}-home-drawio-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.artifact }}-home-drawio-
      - name: Download beardist
        run: |
          curl -L -o beardist.tar.xz https://github.com/bearcove/beardist/releases/download/v1.0.2/aarch64-apple-darwin.tar.xz
          tar -xf beardist.tar.xz
          chmod +x beardist
          sudo mv beardist /usr/local/bin/
      - name: Install required dependencies
        run: |
          # Install pnpm package manager and bun via tap
          brew tap oven-sh/bun
          brew install node pnpm cargo-sweep cargo-nextest just bun coreutils xz
      - name: Build
        run: |
          beardist build
  linux-build:
    strategy:
      matrix:
        include:
          - runs-on: depot-ubuntu-24.04-4
            artifact: x86_64-unknown-linux-gnu
          - runs-on: depot-ubuntu-24.04-arm-4
            artifact: aarch64-unknown-linux-gnu
    runs-on: ${{ matrix.runs-on }}
    container:
      image: ghcr.io/bearcove/beardist:latest
    env:
      GH_READWRITE_TOKEN: ${{ secrets.GH_READWRITE_TOKEN }}
      PNPM_HOME: /tmp/cache/pnpm-home
      BEARDIST_CACHE_DIR: /tmp/cache/beardist
      BEARDIST_ARTIFACT_NAME: ${{ matrix.artifact }}
      FORGEJO_READWRITE_TOKEN: ${{ secrets.FORGEJO_READWRITE_TOKEN }}
      CLICOLOR: 1
      CLICOLOR_FORCE: 1
      IMAGE_PLATFORM: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: /tmp/cache
          key: ${{ runner.os }}-${{ matrix.artifact }}-home-drawio-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.artifact }}-home-drawio-
      - name: Build
        shell: bash
        run: |
          beardist build
  trigger-formula-update:
    needs: [mac-build, linux-build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: depot-ubuntu-24.04-2
    env:
      GH_READWRITE_TOKEN: ${{ secrets.GH_READWRITE_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Trigger formula update
        run: |
          curl -f -X POST \
            -H "Authorization: token $GH_READWRITE_TOKEN" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -d '{"ref": "main", "inputs": {"repository": "'$GITHUB_REPOSITORY'"}}' \
            https://api.github.com/repos/bearcove/tap/actions/workflows/bump.yml/dispatches
